# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Demo-gradle-project

on:
  workflow_dispatch:
    inputs:
      version:
        description: Demo project
        required: true

env:
#   #ARTIFACT_FOLDER_NAME: ""
  AWS_REGION: "us-east-1"
#   #BUCKET: "my-tf-test-bucket-25072022"

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        # build-root-directory: 
        arguments: buildZip

    - name: Get the lib name
      run: |
          mv ./build/libs/*.jar ./build/libs/newsroom_nmc-dgs.jar
          echo "::set-output name=lib_name::$(ls build/libs | grep -v "plain" | grep nmc)"
      id: lib

    - name: Copy jar to artifact directory
      run: cp ./build/libs/${{ steps.lib.outputs.lib_name }} ./artifact/

    # - name: Upload build artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: package
    #     path: 
    
    # - name: Gradle Build
    #   #uses: gradle/gradle-build-action@v2
    #   run: ./gradlew build
    
    # - name: Publish test results
    #   uses: enricoMi/Publish-unit-test-result-action@v1
    #   if: always()
    #   with:
    #     files: "./build/test-results/**/*.xml"

    # - name: Gradle release
    #   uses: gradle/gradle-build-action@v2
    #   with:
    #     build-root-directory: 
    #     arguments: release -Prelease.customUsername=$GITHUB_ACTOR -Prelease.customPassword=${{ secrets.GITHUB_TOKEN }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

    # - uses: actions/github-script@v6
    #   id: get-version
    #   with:
    #     script: |
    #       const { readdirSync } = require('fs')
    #       let dirs = readdirSync(process + '/build/distributions');
    #       let file = dirs.find(element => element.endsWith(".zip"));
    #       let match = /([0-9]+([.][0-9]+)+(-SNAPSHOT)?)/.exec(file);
    #       console.log("Found version: "+match[0])
    #       return match[0]
    #     result-encoding: string

    - name: Prepare an artifact
      run: |
        pushd ./artifact
        zip ../newsroom_nmc-dgs.zip *
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        # upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: newsroom_nmc-dgs.zip
        asset_name: newsroom_nmc-dgs.zip
        asset_content_type: application/zip

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Download dd-java-agent
      run: wget -O ./artifact/dd-java-agent.jar https://dtdg.co/latest-java-tracer

    - name: Upload to s3
      # env:
      #   VERSION: ${{ steps.get-version.outputs.result }}
      run: |
        pwd
        ls -l /home/runner/work/my-project/my-project/build/distributions
        aws s3 cp ./build/distributions/*.zip s3://my-tf-test-bucket-25072022 --recursive 


      
         
